# promise 的基本操作


## resolve 传递  
p2 使用p1 的状态 , 如果p1 是resolve 那 p2 也将是 resolve , 如果 p1 的状态是 reject 那 p2 也是 reject , 如果 p1 的状态已经是 resolve / reject , 那p2 将会立刻执行 回调
```javascript
const p1 = new Promise ((res , rej) =>{
    setTimeout(() => {
        rej()
    },3000)
})

const p2 = new Promise((res , rej) => {
    res(p1)
})
p2.then(res =>{
    console.log('res')
}).catch(err => {
    console.log('err')
})

// err 
```

## 定义状态之后并不会中断执行  

```javascript 
const p = new Promise ((res , rej ) => {
    console.log(1)
    res()
    console.log(2)
})
// 1 , 2 
```
如果要中断 请使用 return 进行终止 

```javascript 
const p = new Promise ((res , rej ) => {
    console.log(1)
    return res()
    console.log(2)
})
// 1
```


## Promise.prototype.then() 传递
使用return 将你需要传递的值 传入下一个 promise   

```javascript 
Promise.resolve(1).then((value ) => {
    return value + 1 
}).then((value ) => {
    console.log(value)
})
// 2 
```


## Promise 的错误处理
如果Promise 状态已经改变成 resloved  , 在抛出错误是无效的 !!!  
并且Promise 对象的错误具有冒泡机制, 会一直向后传递, 直到捕获为止 


```javascript 
Promise.reject().then(res =>{
    console.log(1)
    const a = y + 1 ; 
}).catch(() => {
    console.log(`error`)
}).then(() => {
    const x = n + 1 ; 
}).catch(() => {
    console.log(`error`)
})
// error error 
```


##  Nodejs 的 unhandledRejection 事件  
专门监听未捕获的 reject 错误 
```javascript 

Promise.reject(1).then(res => {
    
})
process.on('unhandledRejection' , function (err , p) {
    console.log(err)
})
// 1 
```



## Promise.all 方法  
必须所有的promise 状态都为 resolve  
```javascript 
const p1 = new Promise((res) => {
    res(1)
})
const p2 = new Promise((res) => {
    res(2)
})
const p3 = new Promise((res) => {
    res(3)
})

Promise.all([p1 , p2 , p3]).then(res =>{
    console.log(res)
})

```

只能捕获到第一个 reject 状态 
```javascript 

const p1 = new Promise((res) => {
    res(1)
})
const p2 = new Promise((res , rej) => {
    rej(2)
})
const p3 = new Promise((res , rej) => {
    rej(3)
})

Promise.all([p1 , p2 , p3]).then(res =>{
    console.log(res)
}).catch(err =>{
    console.log(err)
})
// 2 
```
## Promise.race 方法

只需要有其中一个promise 状态为 reject ,则直接变换状态为 reject 

```javascript 
const p1 = new Promise((res) => {
    res(1)
})
const p2 = new Promise((res , rej) => {
    res(2)
})
const p3 = new Promise((res , rej) => {
    res(3)
})

Promise.race([p1 , p2 , p3]).then(res =>{
    console.log(res)
}).catch(err =>{
    console.log(err)
})
```


## Promise.resolve() 
接受参数
+  Promise 对象则直接返回
+  thenable 对象,指拥有 then 方法的对象 , resolve 将其直接包装成Promise , 并且立即执行他的.then方法  
+  如果不是具有 then方法或者不是对象 , 直接返回一个新的Promise ,并且状态为 resolve 
+  没有参数将会返回一个 状态为 resolve 的 Promise 对象 

## Promise.reject()   
reject 会返回一个新的promise 对象 , 状态为 : reject 

:::tip 
reject方法里面的参数将会原封不动的返回 .... , 不想resolve 一样 做处理  
:::



## done 和 finally 

/ 如果 done 处于Promise 的末端 ,那么他将会铺货Promise 链的 异常, 进行抛出 

/ finally  不管咋样都会执行 


